# -*- coding: utf-8 -*-
"""Main_ET_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNLwsZP8cv8AIigBgOd9XStbYkPvbYKW
"""

# LAst UPdated code latest 01: 03 am on 25//09//2026

"""
================================================================================
AlphaRadar AI - Indian Stock Market 📈Real-Time News 🌐Filter & Telegram Alert Bot
(Anti-Overload Safe Build: Smart Filtering, Shuffled Feeds, ⏰Hourly Pacing & Menu)
================================================================================
"""

import os
import re
import sys
import time
import random
import hashlib
import sqlite3
import threading
import traceback
import json
from http.server import BaseHTTPRequestHandler, HTTPServer
from datetime import datetime, timezone, timedelta

# ============================================================================
# 🕒 TIMEZONE SETUP (INDIAN STANDARD TIME - IST +05:30)
# ============================================================================
IST = timezone(timedelta(hours=5, minutes=30))

try:
    import feedparser
except ImportError:
    os.system("pip install -q feedparser")
    import feedparser

try:
    import requests
except ImportError:
    os.system("pip install -q requests")
    import requests

try:
    from google import genai
except ImportError:
    os.system("pip install -q google-genai")
    from google import genai


def log(msg: str) -> None:
    timestamp = datetime.now(IST).strftime("%H:%M:%S")
    print(f"[{timestamp}] {msg}", flush=True)


# ============================================================================
# CONFIGURATION — EXACT VARIABLE NAMES (COLAB SECRETS + RENDER ENV)
# ============================================================================
BOT_TOKEN = "TELEGRAM_BOT_TOKEN"
CHAT_ID = "TELEGRAM_CHAT_ID"
GEMINI_API_KEY = "GEMINI_API_KE"
GEMINI_API_KEY_2 = "GEMINI_API_KEY_2"

try:
    from google.colab import userdata

    BOT_TOKEN = userdata.get("TELEGRAM_BOT_TOKEN") or ""
    c_id = userdata.get("TELEGRAM_CHAT_ID")
    CHAT_ID = str(c_id) if c_id is not None else ""
    GEMINI_API_KEY = userdata.get("GEMINI_API_KEY") or ""
    GEMINI_API_KEY_2 = userdata.get("GEMINI_API_KEY_2") or ""
except (ImportError, Exception):
    pass

if not BOT_TOKEN:
    BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

if not CHAT_ID:
    CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

if not GEMINI_API_KEY:
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

if not GEMINI_API_KEY_2:
    GEMINI_API_KEY_2 = os.getenv("GEMINI_API_KEY_2", "")

BOT_TOKEN = BOT_TOKEN.strip().replace('"', "").replace("'", "")
CHAT_ID = CHAT_ID.strip().replace('"', "").replace("'", "")
GEMINI_API_KEY = GEMINI_API_KEY.strip().replace('"', "").replace("'", "")
GEMINI_API_KEY_2 = GEMINI_API_KEY_2.strip().replace('"', "").replace("'", "")

ACTIVE_KEY_INDEX = 1  # 1 = Key 1, 2 = Key 2

PORT = int(os.getenv("PORT", "10000"))
RENDER_EXTERNAL_URL = os.getenv("RENDER_EXTERNAL_URL", "")
SELF_PING_INTERVAL_SECONDS = 600

DB_PATH = "news_history.db"

GEMINI_MODEL_CANDIDATES = [
    "gemini-3.5-flash-lite",
    "gemini-flash-latest",
    "gemini-3.8-flash",
    "gemini-3.7-flash",
]
MODEL_NAME = None

CHECK_INTERVAL_SECONDS = 3600  # 1 Hour Hourly Cycle
REQUEST_TIMEOUT = 25
GEMINI_DAILY_CALL_BUDGET = 100

# 🛡️ BALANCED SAFE HOURLY LIMITS
MAX_ALERTS_PER_CYCLE = 4       # Max 4 alerts delivered per cycle
MAX_ITEMS_TO_EVALUATE = 10     # Max 10 Gemini calls per scan cycle
API_PAUSE_SECONDS = 5.0        # 5 second delay between API calls

GEMINI_MAX_RETRIES_PER_MODEL = 2
GEMINI_RETRY_BASE_DELAY = 3
GEMINI_RESOLUTION_COOLDOWN_SECONDS = 300
_last_model_resolution_attempt = 0.0

LAST_UPDATE_ID = 0

# 🏷️ USER CUSTOM SEARCH KEYWORDS & TOGGLE (Default Disabled)
ENABLE_CUSTOM_KEYWORDS = False
USER_CUSTOM_KEYWORDS = [
    "orders", "splits", "multibagger", "bonus issue", "order win",
    "acquisition", "expansion", "patent", "breakout", "dividend"
]

LAST_RUN_STATS = {
    "quota_exhausted": False,
    "limit_type": "None",
    "quota_value_at_exhaust": 0,
    "exhaust_time": "N/A",
    "duplicate_count": 0,
    "pre_filtered_count": 0,
    "sent_count": 0,
    "last_run_timestamp": "Never"
}

RSS_FEEDS = {
    "Economic Times Markets": "https://economictimes.indiatimes.com/markets/rssfeeds/2146842.cms",
    "Livemint Markets": "https://www.livemint.com/rss/markets",
}


# ============================================================================
# SMART NOISE vs HOT KEYWORDS PRE-FILTER
# ============================================================================
def is_potentially_important(title: str) -> bool:
    text = title.lower()

    if ENABLE_CUSTOM_KEYWORDS:
        for kw in USER_CUSTOM_KEYWORDS:
            if kw.lower() in text:
                return True

    junk = [
        "closing bell", "top 10", "listicle", "daily brief", "morning update",
        "evening update", "photo gallery", "market wrap", "markets closed",
        "stock price live updates", "stock price highlights", "share price live updates",
        "trading update", "closure of trading window"
    ]
    for j in junk:
        if j in text:
            return False

    hot = [
        "q1", "q2", "q3", "q4", "earnings", "profit", "loss", "revenue", "sales", "ebitda",
        "merger", "acquisition", "ipo", "listing", "surge", "tumble", "plunge", "rally", "jump",
        "drops", "hits", "record high", "52-week", "rbi", "fed", "sebi", "dividend", "bonus",
        "split", "stake", "buyback", "upgrade", "downgrade", "target", "order", "contract",
        "deal", "shares", "stock", "nifty", "sensex", "tata", "reliance", "adani", "hdfc",
        "infosys", "icici", "sbi", "board meeting", "sanction", "approval"
    ]
    for h in hot:
        if h in text:
            return True

    return False


# ============================================================================
# HEALTH-CHECK HTTP SERVER & SELF-PING
# ============================================================================
class _HealthCheckHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"AlphaRadar AI - Bot is running.")

    def do_HEAD(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()

    def log_message(self, format, *args):
        pass


class ReusableHTTPServer(HTTPServer):
    allow_reuse_address = True


def start_health_check_server() -> None:
    def _serve():
        try:
            server = ReusableHTTPServer(("0.0.0.0", PORT), _HealthCheckHandler)
            log(f"✅ Health-check server listening on 0.0.0.0:{PORT}")
            server.serve_forever()
        except Exception as e:
            log(f"⚠️ Health-check notice: {e}")

    threading.Thread(target=_serve, daemon=True, name="health-check-server").start()


def start_self_ping_thread() -> None:
    if not RENDER_EXTERNAL_URL:
        return

    ping_url = RENDER_EXTERNAL_URL.rstrip("/") + "/"

    def _ping_loop():
        while True:
            time.sleep(SELF_PING_INTERVAL_SECONDS)
            try:
                r = requests.get(ping_url, timeout=10)
                log(f"🔁 Self-ping to {ping_url} -> HTTP {r.status_code}")
            except Exception as e:
                log(f"⚠️ Self-ping notice: {e}")

    threading.Thread(target=_ping_loop, daemon=True, name="self-ping").start()


# ============================================================================
# DATABASE LAYER & 24HR AUTO-ROLLING TEMP QUOTA TRACKER
# ============================================================================
def init_db() -> None:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS sent_news (
                news_id      TEXT PRIMARY KEY,
                title        TEXT,
                source       TEXT,
                status       TEXT,
                processed_at TEXT
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS gemini_usage (
                usage_date  TEXT PRIMARY KEY,
                calls_used  INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS temp_quota (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                calls_used INTEGER DEFAULT 0,
                start_time REAL DEFAULT 0,
                level_alerted INTEGER DEFAULT 0
            )
            """
        )
        cur.execute("INSERT OR IGNORE INTO temp_quota (id, calls_used, start_time, level_alerted) VALUES (1, 0, 0, 0)")
        conn.commit()
        conn.close()
        log("✅ Database initialized successfully.")
    except sqlite3.DatabaseError:
        if os.path.exists(DB_PATH):
            os.remove(DB_PATH)
        init_db()


def _today_utc_str() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def gemini_calls_used_today() -> int:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute("SELECT calls_used FROM gemini_usage WHERE usage_date = ?", (_today_utc_str(),))
        row = cur.fetchone()
        conn.close()
        return row[0] if row else 0
    except sqlite3.Error:
        return 0


def track_and_check_quota_levels() -> None:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        now = time.time()
        cur.execute("SELECT calls_used, start_time, level_alerted FROM temp_quota WHERE id = 1")
        row = cur.fetchone()

        if not row or row[1] == 0 or (now - row[1]) >= 86400:
            calls_used = 1
            start_time = now
            level_alerted = 0
            cur.execute(
                "UPDATE temp_quota SET calls_used = ?, start_time = ?, level_alerted = ? WHERE id = 1",
                (calls_used, start_time, level_alerted)
            )
        else:
            calls_used = row[0] + 1
            start_time = row[1]
            level_alerted = row[2]
            cur.execute("UPDATE temp_quota SET calls_used = ? WHERE id = 1", (calls_used,))

        conn.commit()
        conn.close()

        alert_msg = None
        new_level = level_alerted

        if calls_used >= 140 and level_alerted < 3:
            alert_msg = "You have crossed 🔥 HIgh Level 3 Quota"
            new_level = 3
        elif calls_used >= 90 and level_alerted < 2:
            alert_msg = "You have crossed 🌕 Mid Level 2 Quota"
            new_level = 2
        elif calls_used >= 45 and level_alerted < 1:
            alert_msg = "You have crossed 🌑 Low Level 1 Quota"
            new_level = 1

        if alert_msg and new_level > level_alerted:
            conn = sqlite3.connect(DB_PATH)
            cur = conn.cursor()
            cur.execute("UPDATE temp_quota SET level_alerted = ? WHERE id = 1", (new_level,))
            conn.commit()
            conn.close()
            send_telegram_summary(f"⚠️ *Quota Alert:*\n{alert_msg}\n*(Current Quota Used: {calls_used})*")

    except Exception as e:
        log(f"⚠️ Temp quota error: {e}")


def record_gemini_call() -> None:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        today = _today_utc_str()
        cur.execute(
            """
            INSERT INTO gemini_usage (usage_date, calls_used) VALUES (?, 1)
            ON CONFLICT(usage_date) DO UPDATE SET calls_used = calls_used + 1
            """,
            (today,),
        )
        conn.commit()
        conn.close()
    except sqlite3.Error:
        pass
    track_and_check_quota_levels()


def gemini_budget_remaining() -> int:
    global GEMINI_DAILY_CALL_BUDGET
    return max(0, GEMINI_DAILY_CALL_BUDGET - gemini_calls_used_today())


def is_news_processed(news_id: str) -> bool:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM sent_news WHERE news_id = ?", (news_id,))
        res = cur.fetchone()
        conn.close()
        return res is not None
    except sqlite3.Error:
        return False


def mark_news_processed(news_id: str, title: str, source: str, status: str) -> None:
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute(
            "INSERT OR REPLACE INTO sent_news (news_id, title, source, status, processed_at) VALUES (?, ?, ?, ?, ?)",
            (news_id, title, source, status, datetime.now(IST).isoformat()),
        )
        conn.commit()
        conn.close()
    except sqlite3.Error:
        pass


def strip_html(raw_html: str) -> str:
    if not raw_html:
        return ""
    text = re.sub(r"<[^>]+>", " ", raw_html)
    return re.sub(r"\s+", " ", text).strip()


def extract_published_time(entry) -> str:
    try:
        if hasattr(entry, "published_parsed") and entry.published_parsed:
            dt_utc = datetime(*entry.published_parsed[:6], tzinfo=timezone.utc)
            dt_ist = dt_utc.astimezone(IST)
            return dt_ist.strftime("%I:%M %p , %d %b")
        elif entry.get("published"):
            raw = entry.get("published").strip()
            return raw[:22]
    except Exception:
        pass
    return datetime.now(IST).strftime("%I:%M %p , %d %b")


def make_news_id(entry) -> str:
    news_id = entry.get("id") or entry.get("link")
    if not news_id:
        news_id = hashlib.md5(entry.get("title", "").encode("utf-8")).hexdigest()
    return news_id


# ============================================================================
# GEMINI MODEL ENGINE & RESOLVER (WITH MULTI-KEY 429 FAILOVER)
# ============================================================================
_genai_client = None


def get_current_api_key() -> str:
    global ACTIVE_KEY_INDEX
    if ACTIVE_KEY_INDEX == 2 and GEMINI_API_KEY_2:
        return GEMINI_API_KEY_2
    return GEMINI_API_KEY


def switch_to_backup_key() -> bool:
    global _genai_client, ACTIVE_KEY_INDEX
    if ACTIVE_KEY_INDEX == 1 and GEMINI_API_KEY_2:
        ACTIVE_KEY_INDEX = 2
        _genai_client = None
        log("🔄 Switched to Gemini API Key 2 due to 429 exhaust on Key 1.")
        send_telegram_summary("⚠️ *Model switched to Gemini API 2 with Gemini key1 is having 429 exhaust error*")
        return True
    return False


def get_genai_client():
    global _genai_client
    if _genai_client is None:
        _genai_client = genai.Client(api_key=get_current_api_key())
    return _genai_client


def resolve_gemini_model(force: bool = False) -> bool:
    global MODEL_NAME, _last_model_resolution_attempt

    if MODEL_NAME is not None:
        return True

    now = time.time()
    if not force and (now - _last_model_resolution_attempt) < GEMINI_RESOLUTION_COOLDOWN_SECONDS:
        return False
    _last_model_resolution_attempt = now

    if gemini_budget_remaining() <= 0:
        log("🛑 Daily Gemini budget exhausted during model resolution.")
        return False

    try:
        client = get_genai_client()
    except Exception as e:
        log(f"❌ Failed to initialize Google GenAI Client: {e}")
        return False

    log("🔍 Testing Gemini candidate models...")
    for candidate in GEMINI_MODEL_CANDIDATES:
        if gemini_budget_remaining() <= 0:
            break
        try:
            log(f"  ↳ Probing candidate model: '{candidate}'...")
            record_gemini_call()
            response = client.models.generate_content(
                model=candidate,
                contents="Reply with the single word: OK",
            )
            text = (getattr(response, "text", "") or "").strip()
            if text:
                MODEL_NAME = candidate
                log(f"✅ Gemini successfully connected! Active Model: '{candidate}'")
                return True
        except Exception as e:
            log(f"  ⚠️ Candidate '{candidate}' not reachable: {e}")
            time.sleep(2)
            continue
    log("❌ Could not resolve any working Gemini candidate model.")
    return False


ANALYSIS_PROMPT_TEMPLATE = """You are a Principal Equity Research Analyst specializing in Indian stock markets (NSE/BSE).

Analyze the following news item strictly for its TRADEABLE market impact.

RULES:
- IGNORE only genuine noise: routine wrap-ups, generic daily summaries, pure opinion columns, listicles.
- Flag anything with concrete effect on a stock, sector, Nifty, or BankNifty — HIGH impact for clear major events, and MEDIUM impact for smaller but tangible developments.
- If low impact or routine noise, respond with EXACTLY: IGNORE
- Do not explain your reasoning.

If high or medium impact, respond in this format:

🚨 **MARKET IMPACT ALERT** 🚨

📌 **Stock / Entity:** [Exact Company Name / Nifty / BankNifty]
💥 **Impact Level:** [🔴 HIGH IMPACT / 🟠 MEDIUM IMPACT]

📝 **Summary:**
• [First concise bullet point]
• [Second concise bullet point]

📊 **Market Bias:** [📈 BULLISH / 📉 BEARISH / ⚖️ NEUTRAL] - [Brief reasoning]

---
NEWS TITLE: {title}
NEWS SUMMARY: {summary}
SOURCE: {source}
---
"""


def analyze_news(entry: dict):
    global MODEL_NAME, LAST_RUN_STATS

    if not MODEL_NAME or gemini_budget_remaining() <= 0:
        return None

    prompt = ANALYSIS_PROMPT_TEMPLATE.format(
        title=entry["title"],
        summary=entry["summary"] or "N/A",
        source=entry["source"],
    )
    client = get_genai_client()
    models_to_try = [MODEL_NAME] + [m for m in GEMINI_MODEL_CANDIDATES if m != MODEL_NAME]

    for model_id in models_to_try:
        if gemini_budget_remaining() <= 0:
            break

        for attempt in range(1, GEMINI_MAX_RETRIES_PER_MODEL + 1):
            if gemini_budget_remaining() <= 0:
                return None
            try:
                log(f"⏳ Gemini [{model_id}] busy, processing... (Safety pause {API_PAUSE_SECONDS}s)")
                time.sleep(API_PAUSE_SECONDS)

                record_gemini_call()
                response = client.models.generate_content(model=model_id, contents=prompt)
                text = (getattr(response, "text", "") or "").strip()

                if not text:
                    raise ValueError("Empty response received from Gemini.")

                if model_id != MODEL_NAME:
                    MODEL_NAME = model_id
                    log(f"🔀 Switched active model to: '{model_id}'")

                return text

            except Exception as e:
                err_str = str(e)
                if "429" in err_str or "RESOURCE_EXHAUSTED" in err_str:
                    log(f"⚡ Google Gemini Quota Limit Triggered on [{model_id}]!")
                    if switch_to_backup_key():
                        client = get_genai_client()
                        continue
                    else:
                        LAST_RUN_STATS["quota_exhausted"] = True
                        LAST_RUN_STATS["limit_type"] = "Google 429 Hard Quota Hit"
                        LAST_RUN_STATS["quota_value_at_exhaust"] = gemini_calls_used_today()
                        LAST_RUN_STATS["exhaust_time"] = datetime.now(IST).strftime("%d %b %Y, %I:%M %p")
                else:
                    log(f"⚠️ Model [{model_id}] error on attempt {attempt}: {err_str[:80]}")
                time.sleep(attempt * 4)
                continue

    return None


# ============================================================================
# TELEGRAM DISPATCH & NOTIFICATIONS
# ============================================================================
def send_telegram_alert(message: str, link: str, published_time: str) -> bool:
    full_message = f"{message}\n\n🕒 *Time & Date :* {published_time}\n🔗 [Read Full Article]({link})"
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": full_message,
        "parse_mode": "Markdown",
        "disable_web_page_preview": False,
    }
    try:
        r = requests.post(url, data=payload, timeout=REQUEST_TIMEOUT)
        return r.status_code == 200
    except Exception as e:
        log(f"❌ Telegram alert dispatch error: {e}")
        return False


def send_telegram_summary(message: str, reply_markup: dict = None) -> bool:
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown",
    }
    if reply_markup:
        payload["reply_markup"] = json.dumps(reply_markup)
    try:
        return requests.post(url, data=payload, timeout=REQUEST_TIMEOUT).status_code == 200
    except Exception:
        return False


# ============================================================================
# INTERACTIVE TELEGRAM DASHBOARD MENU & COMMAND POLLING (5 SEPARATE BUTTONS)
# ============================================================================
def get_main_menu_keyboard():
    toggle_text = "🟢 Custom Keywords: Enabled (Click to Disable)" if ENABLE_CUSTOM_KEYWORDS else "🔴 Custom Keywords: Disabled (Click to Enable)"
    return {
        "inline_keyboard": [
            [{"text": "📊 Bot Status & Quota", "callback_data": "menu_status"}],
            [{"text": "➕ Add Gemini Quota (+50)", "callback_data": "menu_add_quota"}],
            [{"text": "🏷️ Search / View Keywords", "callback_data": "menu_view_keywords"}],
            [{"text": "⏳ Change Interval Time", "callback_data": "menu_change_interval"}],
            [{"text": toggle_text, "callback_data": "menu_toggle_custom_kw"}]
        ]
    }


def get_interval_keyboard():
    return {
        "inline_keyboard": [
            [{"text": "⚡ 30 Minutes", "callback_data": "int_1800"}, {"text": "⏱️ 1 Hour", "callback_data": "int_3600"}],
            [{"text": "⚖️ 2 Hours", "callback_data": "int_7200"}, {"text": "☕ 4 Hours", "callback_data": "int_14400"}],
            [{"text": "🔙 Back to Menu", "callback_data": "menu_back"}]
        ]
    }


def format_interval_text(seconds: int) -> str:
    if seconds < 3600:
        return f"{seconds // 60} minute"
    hours = seconds / 3600
    return f"{int(hours) if hours.is_integer() else hours} ghante"


def get_bot_status_message() -> str:
    calls_used = gemini_calls_used_today()

    if LAST_RUN_STATS["quota_exhausted"]:
        quota_str = f"Exhausted [{LAST_RUN_STATS['limit_type']}] ({LAST_RUN_STATS['quota_value_at_exhaust']}/{GEMINI_DAILY_CALL_BUDGET}) at {LAST_RUN_STATS['exhaust_time']}"
    else:
        quota_str = f"{calls_used}/{GEMINI_DAILY_CALL_BUDGET} (Active - Under Limit)"

    if LAST_RUN_STATS["duplicate_count"] > 0:
        news_data_str = f"found Duplicate news ({LAST_RUN_STATS['duplicate_count']})"
    else:
        news_data_str = f"{LAST_RUN_STATS['sent_count']} news sent"

    kw_status = "Enabled 🟢" if ENABLE_CUSTOM_KEYWORDS else "Disabled 🔴"

    return (
        "📊 *AlphaRadar Bot Status (IST)*\n\n"
        f"⚙️ *Active Model:* `{MODEL_NAME or 'Auto-Resolving'}`\n"
        f"🔑 *Active Key:* `Key {ACTIVE_KEY_INDEX}`\n"
        f"🏷️ *Custom Keywords Search:* `{kw_status}`\n"
        f"⏳ *Check Interval:* {format_interval_text(CHECK_INTERVAL_SECONDS)}\n"
        f"🎯 *Cycle Alert Cap:* {MAX_ALERTS_PER_CYCLE} Alerts (Safety Ceiling: {MAX_ITEMS_TO_EVALUATE} checks)\n"
        f"📊 *Quota Condition:* `{quota_str}`\n"
        f"📰 *Last News Data:* `{news_data_str}`\n"
        f"🛡️ *Noise Filtered Pre-AI:* {LAST_RUN_STATS['pre_filtered_count']}\n"
        f"🕒 *Last Cycle Time:* {LAST_RUN_STATS['last_run_timestamp']}"
    )


def telegram_polling():
    global CHECK_INTERVAL_SECONDS, LAST_UPDATE_ID, GEMINI_DAILY_CALL_BUDGET, USER_CUSTOM_KEYWORDS, ENABLE_CUSTOM_KEYWORDS
    log("🤖 Telegram Command & Menu Polling started.")

    while True:
        try:
            url = f"https://api.telegram.org/bot{BOT_TOKEN}/getUpdates"
            params = {"offset": LAST_UPDATE_ID + 1, "timeout": 10}
            res = requests.get(url, params=params, timeout=15).json()

            if res.get("ok"):
                for result in res["result"]:
                    LAST_UPDATE_ID = result["update_id"]

                    if "callback_query" in result:
                        cb = result["callback_query"]
                        cb_data = cb.get("data")
                        cb_chat_id = str(cb.get("message", {}).get("chat", {}).get("id", ""))

                        if cb_chat_id != CHAT_ID:
                            continue

                        if cb_data == "menu_status":
                            send_telegram_summary(get_bot_status_message(), get_main_menu_keyboard())

                        elif cb_data == "menu_toggle_custom_kw":
                            ENABLE_CUSTOM_KEYWORDS = not ENABLE_CUSTOM_KEYWORDS
                            status_label = "Enabled 🟢" if ENABLE_CUSTOM_KEYWORDS else "Disabled 🔴"
                            send_telegram_summary(
                                f"🏷️ *Custom Keyword Search Status Updated*\n\nAb Custom Keyword Search: *{status_label}* hai.",
                                get_main_menu_keyboard()
                            )

                        elif cb_data == "menu_add_quota":
                            GEMINI_DAILY_CALL_BUDGET += 50
                            LAST_RUN_STATS["quota_exhausted"] = False
                            LAST_RUN_STATS["limit_type"] = "None"
                            resolve_gemini_model(force=True)
                            send_telegram_summary(
                                f"✅ *Quota Extended by 50!*\n\n"
                                f"Naya Budget: *{GEMINI_DAILY_CALL_BUDGET} calls*\n"
                                f"Used Today: *{gemini_calls_used_today()}*\n"
                                f"Remaining: *{gemini_budget_remaining()}*",
                                get_main_menu_keyboard()
                            )

                        elif cb_data == "menu_view_keywords":
                            kw_list = ", ".join([f"`{k}`" for k in USER_CUSTOM_KEYWORDS])
                            status_label = "Enabled 🟢" if ENABLE_CUSTOM_KEYWORDS else "Disabled 🔴"
                            msg = (
                                f"🏷️ *Search Keywords List* [Status: {status_label}]:\n\n"
                                f"{kw_list}\n\n"
                                "💡 *Naya Keyword Add Karein:*\n"
                                "Chat mein type karke send karein:\n"
                                "`/addkeyword yourword` (e.g. `/addkeyword bonus`)"
                            )
                            send_telegram_summary(msg, get_main_menu_keyboard())

                        elif cb_data == "menu_change_interval":
                            send_telegram_summary("⏳ *Select New Scan Interval:*", get_interval_keyboard())

                        elif cb_data.startswith("int_"):
                            sec = int(cb_data.split("_")[1])
                            CHECK_INTERVAL_SECONDS = sec
                            send_telegram_summary(
                                f"✅ Scan interval updated to *{format_interval_text(CHECK_INTERVAL_SECONDS)}*.",
                                get_main_menu_keyboard()
                            )

                        elif cb_data == "menu_back":
                            send_telegram_summary(
                                "👋 *AlphaRadar News🌐 Dashboard*\n\nNeeche diye gaye option se bot operate karein:",
                                get_main_menu_keyboard()
                            )

                        requests.get(f"https://api.telegram.org/bot{BOT_TOKEN}/answerCallbackQuery", params={"callback_query_id": cb.get("id")})

                    elif "message" in result:
                        msg_obj = result["message"]
                        text = str(msg_obj.get("text", "")).strip()
                        msg_chat_id = str(msg_obj.get("chat", {}).get("id", ""))

                        if msg_chat_id != CHAT_ID:
                            continue

                        if text.lower() in ["hi", "hello", "/start", "/menu", "menu"]:
                            dashboard_text = (
                                "👋 *AlphaRadar News🌐 Dashboard*\n\n"
                                "Neeche diye gaye option se bot operate karein:"
                            )
                            send_telegram_summary(dashboard_text, get_main_menu_keyboard())

                        elif text.lower().startswith("/addkeyword"):
                            parts = text.split(maxsplit=1)
                            if len(parts) > 1 and parts[1].strip():
                                new_kw = parts[1].strip().lower()
                                if new_kw not in USER_CUSTOM_KEYWORDS:
                                    USER_CUSTOM_KEYWORDS.append(new_kw)
                                    send_telegram_summary(f"✅ Keyword added: `{new_kw}`\nAb is par priority impact check hoga!")
                                else:
                                    send_telegram_summary(f"ℹ️ Keyword `{new_kw}` already included hai.")
                            else:
                                send_telegram_summary("⚠️ Format: `/addkeyword multibagger`")

        except Exception:
            pass
        time.sleep(2)


# ============================================================================
# RSS NEWS INGESTION & PROCESSING
# ============================================================================
def fetch_all_feeds() -> list:
    all_entries = []
    for name, url in RSS_FEEDS.items():
        try:
            feed = feedparser.parse(url)
            count = 0
            for entry in feed.entries:
                title = entry.get("title", "").strip()
                link = entry.get("link", "").strip()
                if not title or not link:
                    continue

                published_str = extract_published_time(entry)

                all_entries.append({
                    "id": make_news_id(entry),
                    "title": title,
                    "summary": strip_html(entry.get("summary", "") or entry.get("description", "")),
                    "link": link,
                    "source": name,
                    "published_time": published_str
                })
                count += 1
            log(f"📰 Fetched {count} entries from '{name}'.")
        except Exception as e:
            log(f"❌ Error fetching '{name}': {e}")
    return all_entries


def run_cycle() -> None:
    global LAST_RUN_STATS
    log("=" * 40)
    log("🚀 --- Starting scan cycle ---")
    log("=" * 40)
    current_time_str = datetime.now(IST).strftime("%d %b %Y, %I:%M %p")
    LAST_RUN_STATS["last_run_timestamp"] = current_time_str

    if not MODEL_NAME:
        log("🔍 Active model not found. Resolving Gemini...")
        resolve_gemini_model(force=True)

    # 1. Cycle shuru hone par Quota Exhaustion Check
    if gemini_budget_remaining() <= 0:
        LAST_RUN_STATS["quota_exhausted"] = True
        LAST_RUN_STATS["limit_type"] = "Local Daily Budget Reached"
        LAST_RUN_STATS["quota_value_at_exhaust"] = gemini_calls_used_today()
        LAST_RUN_STATS["exhaust_time"] = current_time_str
        log("🛑 Daily Gemini budget exhausted! Skipping cycle.")

        quota_hit_msg = (
            "🛑 *Daily Gemini Quota Limit Exhausted!*\n\n"
            f"Daily Limit: *{GEMINI_DAILY_CALL_BUDGET} calls*\n"
            f"Calls Used Today: *{gemini_calls_used_today()}*\n\n"
            "⚠️ Upper limit reach hone ke kaaran news scanning ruka hua hai.\n"
            "👉 Quota badhane ke liye neeche button par click karein:"
        )
        send_telegram_summary(quota_hit_msg, get_main_menu_keyboard())
        return

    log(f"📊 Budget remaining today: {gemini_budget_remaining()}/{GEMINI_DAILY_CALL_BUDGET} | Target Alerts: {MAX_ALERTS_PER_CYCLE}")

    entries = fetch_all_feeds()
    random.shuffle(entries)
    log(f"📰 Total {len(entries)} items collected and randomly shuffled.")

    if not entries:
        log("⚠️ No entries found in RSS feeds this cycle.")
        return

    new_alerts = 0
    items_evaluated = 0
    duplicate_count = 0
    pre_filtered_count = 0
    budget_exhausted_during_run = False

    for idx, entry in enumerate(entries, 1):
        if new_alerts >= MAX_ALERTS_PER_CYCLE:
            log(f"🛑 Target cap of {MAX_ALERTS_PER_CYCLE} alerts reached for this cycle.")
            break

        if items_evaluated >= MAX_ITEMS_TO_EVALUATE:
            log(f"⏹️ Checked safety ceiling of {MAX_ITEMS_TO_EVALUATE} items. Stopping scan.")
            break

        if is_news_processed(entry["id"]):
            duplicate_count += 1
            continue

        if not is_potentially_important(entry["title"]):
            mark_news_processed(entry["id"], entry["title"], entry["source"], "pre-filtered")
            pre_filtered_count += 1
            continue

        # 2. Mid-Cycle Quota Exhaustion Check
        if gemini_budget_remaining() <= 0:
            LAST_RUN_STATS["quota_exhausted"] = True
            LAST_RUN_STATS["limit_type"] = "Local Daily Budget Reached"
            LAST_RUN_STATS["quota_value_at_exhaust"] = gemini_calls_used_today()
            LAST_RUN_STATS["exhaust_time"] = datetime.now(IST).strftime("%d %b %Y, %I:%M %p")
            log("🛑 Daily Gemini budget ran out mid-cycle.")
            budget_exhausted_during_run = True

            send_telegram_summary(
                f"🛑 *Upper Limit Quota Hit ({GEMINI_DAILY_CALL_BUDGET}/{GEMINI_DAILY_CALL_BUDGET})!*\n\n"
                "Scan cycle beech me hi ruk gaya hai. Quota badhane ke liye Dashboard se '+ Add Gemini Quota' karein.",
                get_main_menu_keyboard()
            )
            break

        log("-" * 35)
        log(f"📌 Checking Item [{items_evaluated + 1}/{MAX_ITEMS_TO_EVALUATE}] | Alerts Sent: [{new_alerts}/{MAX_ALERTS_PER_CYCLE}]")
        log(f"   Headline: \"{entry['title']}\"")

        analysis = analyze_news(entry)

        if analysis is None:
            log("   ↳ ⚠️ Gemini analysis failed or timed out. Skipping.")
            continue

        items_evaluated += 1

        if analysis.upper().startswith("IGNORE"):
            mark_news_processed(entry["id"], entry["title"], entry["source"], "ignored")
            log("   ↳ 😴 Result: Evaluated as Routine/Low Impact (IGNORED)")
            continue

        log("   ↳ 🔥 Result: HIGH/MEDIUM IMPACT DETECTED! Sending to Telegram...")
        if send_telegram_alert(analysis, entry["link"], entry.get("published_time", "")):
            mark_news_processed(entry["id"], entry["title"], entry["source"], "sent")
            new_alerts += 1
            log("   ↳ ✅ Telegram Alert sent successfully!")
        else:
            mark_news_processed(entry["id"], entry["title"], entry["source"], "failed")
            log("   ↳ ❌ Telegram Alert dispatch failed.")

    LAST_RUN_STATS["duplicate_count"] = duplicate_count
    LAST_RUN_STATS["pre_filtered_count"] = pre_filtered_count
    LAST_RUN_STATS["sent_count"] = new_alerts

    log("=" * 40)
    log(f"📊 Summary: Duplicates={duplicate_count}, Pre-filtered Noise={pre_filtered_count}, AI Checked={items_evaluated}, Alerts Sent={new_alerts}")
    log("=" * 40)

    interval_display = format_interval_text(CHECK_INTERVAL_SECONDS)
    quota_reason_note = "\n⚠️ *Scan Quota Limit Reached hone par roka gaya.*" if budget_exhausted_during_run else ""

    closing_msg = (
        "🔄 *News Scan Completed*\n"
        f"✅ Alerts Sent: {new_alerts}\n"
        f"🛡️ Checked: {items_evaluated}\n"
        f"⚙️ Engine: `Gemini`\n"
        f"📊 Daily Quota Used: {gemini_calls_used_today()}/{GEMINI_DAILY_CALL_BUDGET}"
        f"{quota_reason_note}\n\n"
        f"Ab next >> news📢 tumhe *{interval_display}* ⏰ baad milegi. 👀"
    )
    send_telegram_summary(closing_msg)
    log(f"--- Cycle complete: {new_alerts} alerts sent ---")


# ============================================================================
# MAIN APPLICATION ENTRY POINT WITH 4-HOUR AUTO STATUS
# ============================================================================
def main() -> None:
    log("=" * 60)
    log(" AlphaRadar AI starting (Safe Pacing + Smart Pre-Filter + 4h Status) ")
    log("=" * 60)

    start_health_check_server()
    start_self_ping_thread()

    missing = []
    if not BOT_TOKEN:
        missing.append("TELEGRAM_BOT_TOKEN")
    if not CHAT_ID:
        missing.append("TELEGRAM_CHAT_ID")
    if not GEMINI_API_KEY:
        missing.append("GEMINI_API_KEY")

    if missing:
        log("❌ Required credentials missing:")
        for item in missing:
            log(f"   ↳ {item}")
        return

    init_db()
    resolve_gemini_model(force=True)

    threading.Thread(target=telegram_polling, daemon=True, name="telegram-poll").start()

    send_telegram_summary(
        "🚀 *AlphaRadar AI Connected Successfully!*\n"
        "⚡ *Smart Pre-Filtering & Anti-Overload Active*\n"
        f"🎯 Alert Target: `Max {MAX_ALERTS_PER_CYCLE} alerts per cycle`\n\n"
        "Check Status & open the Dashboard any time."
    )

    cycle_count = 0
    while True:
        try:
            run_cycle()
            cycle_count += 1

            # 🕒 AUTO STATUS EVERY 6 HOURS (After every 6 cycles)
            if cycle_count % 6 == 0:
                log("📢 Sending scheduled 6-Hour System & Quota Status to Telegram...")
                auto_status_msg = (
                    "⏰ *6-Hour Scheduled System & Quota Report*\n\n"
                    + get_bot_status_message()
                )
                send_telegram_summary(auto_status_msg)

        except Exception:
            traceback.print_exc()

        elapsed = 0
        while elapsed < CHECK_INTERVAL_SECONDS:
            time.sleep(1)
            elapsed += 1


if __name__ == "__main__":
    main()
